package com.mmbao.redis.dao.mybatis.domain;

import com.mmbao.redis.util.page.Page;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XmallDxDlDzExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public XmallDxDlDzExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDzIdIsNull() {
            addCriterion("DZ_ID is null");
            return (Criteria) this;
        }

        public Criteria andDzIdIsNotNull() {
            addCriterion("DZ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDzIdEqualTo(String value) {
            addCriterion("DZ_ID =", value, "dzId");
            return (Criteria) this;
        }

        public Criteria andDzIdNotEqualTo(String value) {
            addCriterion("DZ_ID <>", value, "dzId");
            return (Criteria) this;
        }

        public Criteria andDzIdGreaterThan(String value) {
            addCriterion("DZ_ID >", value, "dzId");
            return (Criteria) this;
        }

        public Criteria andDzIdGreaterThanOrEqualTo(String value) {
            addCriterion("DZ_ID >=", value, "dzId");
            return (Criteria) this;
        }

        public Criteria andDzIdLessThan(String value) {
            addCriterion("DZ_ID <", value, "dzId");
            return (Criteria) this;
        }

        public Criteria andDzIdLessThanOrEqualTo(String value) {
            addCriterion("DZ_ID <=", value, "dzId");
            return (Criteria) this;
        }

        public Criteria andDzIdLike(String value) {
            addCriterion("DZ_ID like", value, "dzId");
            return (Criteria) this;
        }

        public Criteria andDzIdNotLike(String value) {
            addCriterion("DZ_ID not like", value, "dzId");
            return (Criteria) this;
        }

        public Criteria andDzIdIn(List<String> values) {
            addCriterion("DZ_ID in", values, "dzId");
            return (Criteria) this;
        }

        public Criteria andDzIdNotIn(List<String> values) {
            addCriterion("DZ_ID not in", values, "dzId");
            return (Criteria) this;
        }

        public Criteria andDzIdBetween(String value1, String value2) {
            addCriterion("DZ_ID between", value1, value2, "dzId");
            return (Criteria) this;
        }

        public Criteria andDzIdNotBetween(String value1, String value2) {
            addCriterion("DZ_ID not between", value1, value2, "dzId");
            return (Criteria) this;
        }

        public Criteria andDzTypeIsNull() {
            addCriterion("DZ_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDzTypeIsNotNull() {
            addCriterion("DZ_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDzTypeEqualTo(String value) {
            addCriterion("DZ_TYPE =", value, "dzType");
            return (Criteria) this;
        }

        public Criteria andDzTypeNotEqualTo(String value) {
            addCriterion("DZ_TYPE <>", value, "dzType");
            return (Criteria) this;
        }

        public Criteria andDzTypeGreaterThan(String value) {
            addCriterion("DZ_TYPE >", value, "dzType");
            return (Criteria) this;
        }

        public Criteria andDzTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DZ_TYPE >=", value, "dzType");
            return (Criteria) this;
        }

        public Criteria andDzTypeLessThan(String value) {
            addCriterion("DZ_TYPE <", value, "dzType");
            return (Criteria) this;
        }

        public Criteria andDzTypeLessThanOrEqualTo(String value) {
            addCriterion("DZ_TYPE <=", value, "dzType");
            return (Criteria) this;
        }

        public Criteria andDzTypeLike(String value) {
            addCriterion("DZ_TYPE like", value, "dzType");
            return (Criteria) this;
        }

        public Criteria andDzTypeNotLike(String value) {
            addCriterion("DZ_TYPE not like", value, "dzType");
            return (Criteria) this;
        }

        public Criteria andDzTypeIn(List<String> values) {
            addCriterion("DZ_TYPE in", values, "dzType");
            return (Criteria) this;
        }

        public Criteria andDzTypeNotIn(List<String> values) {
            addCriterion("DZ_TYPE not in", values, "dzType");
            return (Criteria) this;
        }

        public Criteria andDzTypeBetween(String value1, String value2) {
            addCriterion("DZ_TYPE between", value1, value2, "dzType");
            return (Criteria) this;
        }

        public Criteria andDzTypeNotBetween(String value1, String value2) {
            addCriterion("DZ_TYPE not between", value1, value2, "dzType");
            return (Criteria) this;
        }

        public Criteria andDzStandardIsNull() {
            addCriterion("DZ_STANDARD is null");
            return (Criteria) this;
        }

        public Criteria andDzStandardIsNotNull() {
            addCriterion("DZ_STANDARD is not null");
            return (Criteria) this;
        }

        public Criteria andDzStandardEqualTo(String value) {
            addCriterion("DZ_STANDARD =", value, "dzStandard");
            return (Criteria) this;
        }

        public Criteria andDzStandardNotEqualTo(String value) {
            addCriterion("DZ_STANDARD <>", value, "dzStandard");
            return (Criteria) this;
        }

        public Criteria andDzStandardGreaterThan(String value) {
            addCriterion("DZ_STANDARD >", value, "dzStandard");
            return (Criteria) this;
        }

        public Criteria andDzStandardGreaterThanOrEqualTo(String value) {
            addCriterion("DZ_STANDARD >=", value, "dzStandard");
            return (Criteria) this;
        }

        public Criteria andDzStandardLessThan(String value) {
            addCriterion("DZ_STANDARD <", value, "dzStandard");
            return (Criteria) this;
        }

        public Criteria andDzStandardLessThanOrEqualTo(String value) {
            addCriterion("DZ_STANDARD <=", value, "dzStandard");
            return (Criteria) this;
        }

        public Criteria andDzStandardLike(String value) {
            addCriterion("DZ_STANDARD like", value, "dzStandard");
            return (Criteria) this;
        }

        public Criteria andDzStandardNotLike(String value) {
            addCriterion("DZ_STANDARD not like", value, "dzStandard");
            return (Criteria) this;
        }

        public Criteria andDzStandardIn(List<String> values) {
            addCriterion("DZ_STANDARD in", values, "dzStandard");
            return (Criteria) this;
        }

        public Criteria andDzStandardNotIn(List<String> values) {
            addCriterion("DZ_STANDARD not in", values, "dzStandard");
            return (Criteria) this;
        }

        public Criteria andDzStandardBetween(String value1, String value2) {
            addCriterion("DZ_STANDARD between", value1, value2, "dzStandard");
            return (Criteria) this;
        }

        public Criteria andDzStandardNotBetween(String value1, String value2) {
            addCriterion("DZ_STANDARD not between", value1, value2, "dzStandard");
            return (Criteria) this;
        }

        public Criteria andVoltageIsNull() {
            addCriterion("VOLTAGE is null");
            return (Criteria) this;
        }

        public Criteria andVoltageIsNotNull() {
            addCriterion("VOLTAGE is not null");
            return (Criteria) this;
        }

        public Criteria andVoltageEqualTo(String value) {
            addCriterion("VOLTAGE =", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageNotEqualTo(String value) {
            addCriterion("VOLTAGE <>", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageGreaterThan(String value) {
            addCriterion("VOLTAGE >", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageGreaterThanOrEqualTo(String value) {
            addCriterion("VOLTAGE >=", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageLessThan(String value) {
            addCriterion("VOLTAGE <", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageLessThanOrEqualTo(String value) {
            addCriterion("VOLTAGE <=", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageLike(String value) {
            addCriterion("VOLTAGE like", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageNotLike(String value) {
            addCriterion("VOLTAGE not like", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageIn(List<String> values) {
            addCriterion("VOLTAGE in", values, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageNotIn(List<String> values) {
            addCriterion("VOLTAGE not in", values, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageBetween(String value1, String value2) {
            addCriterion("VOLTAGE between", value1, value2, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageNotBetween(String value1, String value2) {
            addCriterion("VOLTAGE not between", value1, value2, "voltage");
            return (Criteria) this;
        }

        public Criteria andDelivertIsNull() {
            addCriterion("DELIVERT is null");
            return (Criteria) this;
        }

        public Criteria andDelivertIsNotNull() {
            addCriterion("DELIVERT is not null");
            return (Criteria) this;
        }

        public Criteria andDelivertEqualTo(String value) {
            addCriterion("DELIVERT =", value, "delivert");
            return (Criteria) this;
        }

        public Criteria andDelivertNotEqualTo(String value) {
            addCriterion("DELIVERT <>", value, "delivert");
            return (Criteria) this;
        }

        public Criteria andDelivertGreaterThan(String value) {
            addCriterion("DELIVERT >", value, "delivert");
            return (Criteria) this;
        }

        public Criteria andDelivertGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERT >=", value, "delivert");
            return (Criteria) this;
        }

        public Criteria andDelivertLessThan(String value) {
            addCriterion("DELIVERT <", value, "delivert");
            return (Criteria) this;
        }

        public Criteria andDelivertLessThanOrEqualTo(String value) {
            addCriterion("DELIVERT <=", value, "delivert");
            return (Criteria) this;
        }

        public Criteria andDelivertLike(String value) {
            addCriterion("DELIVERT like", value, "delivert");
            return (Criteria) this;
        }

        public Criteria andDelivertNotLike(String value) {
            addCriterion("DELIVERT not like", value, "delivert");
            return (Criteria) this;
        }

        public Criteria andDelivertIn(List<String> values) {
            addCriterion("DELIVERT in", values, "delivert");
            return (Criteria) this;
        }

        public Criteria andDelivertNotIn(List<String> values) {
            addCriterion("DELIVERT not in", values, "delivert");
            return (Criteria) this;
        }

        public Criteria andDelivertBetween(String value1, String value2) {
            addCriterion("DELIVERT between", value1, value2, "delivert");
            return (Criteria) this;
        }

        public Criteria andDelivertNotBetween(String value1, String value2) {
            addCriterion("DELIVERT not between", value1, value2, "delivert");
            return (Criteria) this;
        }

        public Criteria andReferencePrcIsNull() {
            addCriterion("REFERENCE_PRC is null");
            return (Criteria) this;
        }

        public Criteria andReferencePrcIsNotNull() {
            addCriterion("REFERENCE_PRC is not null");
            return (Criteria) this;
        }

        public Criteria andReferencePrcEqualTo(BigDecimal value) {
            addCriterion("REFERENCE_PRC =", value, "referencePrc");
            return (Criteria) this;
        }

        public Criteria andReferencePrcNotEqualTo(BigDecimal value) {
            addCriterion("REFERENCE_PRC <>", value, "referencePrc");
            return (Criteria) this;
        }

        public Criteria andReferencePrcGreaterThan(BigDecimal value) {
            addCriterion("REFERENCE_PRC >", value, "referencePrc");
            return (Criteria) this;
        }

        public Criteria andReferencePrcGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REFERENCE_PRC >=", value, "referencePrc");
            return (Criteria) this;
        }

        public Criteria andReferencePrcLessThan(BigDecimal value) {
            addCriterion("REFERENCE_PRC <", value, "referencePrc");
            return (Criteria) this;
        }

        public Criteria andReferencePrcLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REFERENCE_PRC <=", value, "referencePrc");
            return (Criteria) this;
        }

        public Criteria andReferencePrcIn(List<BigDecimal> values) {
            addCriterion("REFERENCE_PRC in", values, "referencePrc");
            return (Criteria) this;
        }

        public Criteria andReferencePrcNotIn(List<BigDecimal> values) {
            addCriterion("REFERENCE_PRC not in", values, "referencePrc");
            return (Criteria) this;
        }

        public Criteria andReferencePrcBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REFERENCE_PRC between", value1, value2, "referencePrc");
            return (Criteria) this;
        }

        public Criteria andReferencePrcNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REFERENCE_PRC not between", value1, value2, "referencePrc");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("POSITION is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("POSITION is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(String value) {
            addCriterion("POSITION =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(String value) {
            addCriterion("POSITION <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(String value) {
            addCriterion("POSITION >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(String value) {
            addCriterion("POSITION >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(String value) {
            addCriterion("POSITION <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(String value) {
            addCriterion("POSITION <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLike(String value) {
            addCriterion("POSITION like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotLike(String value) {
            addCriterion("POSITION not like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<String> values) {
            addCriterion("POSITION in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<String> values) {
            addCriterion("POSITION not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(String value1, String value2) {
            addCriterion("POSITION between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(String value1, String value2) {
            addCriterion("POSITION not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andSortnumIsNull() {
            addCriterion("SORTNUM is null");
            return (Criteria) this;
        }

        public Criteria andSortnumIsNotNull() {
            addCriterion("SORTNUM is not null");
            return (Criteria) this;
        }

        public Criteria andSortnumEqualTo(BigDecimal value) {
            addCriterion("SORTNUM =", value, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumNotEqualTo(BigDecimal value) {
            addCriterion("SORTNUM <>", value, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumGreaterThan(BigDecimal value) {
            addCriterion("SORTNUM >", value, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SORTNUM >=", value, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumLessThan(BigDecimal value) {
            addCriterion("SORTNUM <", value, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SORTNUM <=", value, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumIn(List<BigDecimal> values) {
            addCriterion("SORTNUM in", values, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumNotIn(List<BigDecimal> values) {
            addCriterion("SORTNUM not in", values, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SORTNUM between", value1, value2, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SORTNUM not between", value1, value2, "sortnum");
            return (Criteria) this;
        }

        public Criteria andIsDisplayIsNull() {
            addCriterion("IS_DISPLAY is null");
            return (Criteria) this;
        }

        public Criteria andIsDisplayIsNotNull() {
            addCriterion("IS_DISPLAY is not null");
            return (Criteria) this;
        }

        public Criteria andIsDisplayEqualTo(String value) {
            addCriterion("IS_DISPLAY =", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayNotEqualTo(String value) {
            addCriterion("IS_DISPLAY <>", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayGreaterThan(String value) {
            addCriterion("IS_DISPLAY >", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DISPLAY >=", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayLessThan(String value) {
            addCriterion("IS_DISPLAY <", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayLessThanOrEqualTo(String value) {
            addCriterion("IS_DISPLAY <=", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayLike(String value) {
            addCriterion("IS_DISPLAY like", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayNotLike(String value) {
            addCriterion("IS_DISPLAY not like", value, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayIn(List<String> values) {
            addCriterion("IS_DISPLAY in", values, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayNotIn(List<String> values) {
            addCriterion("IS_DISPLAY not in", values, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayBetween(String value1, String value2) {
            addCriterion("IS_DISPLAY between", value1, value2, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andIsDisplayNotBetween(String value1, String value2) {
            addCriterion("IS_DISPLAY not between", value1, value2, "isDisplay");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andDzIdLikeInsensitive(String value) {
            addCriterion("upper(DZ_ID) like", value.toUpperCase(), "dzId");
            return (Criteria) this;
        }

        public Criteria andDzTypeLikeInsensitive(String value) {
            addCriterion("upper(DZ_TYPE) like", value.toUpperCase(), "dzType");
            return (Criteria) this;
        }

        public Criteria andDzStandardLikeInsensitive(String value) {
            addCriterion("upper(DZ_STANDARD) like", value.toUpperCase(), "dzStandard");
            return (Criteria) this;
        }

        public Criteria andVoltageLikeInsensitive(String value) {
            addCriterion("upper(VOLTAGE) like", value.toUpperCase(), "voltage");
            return (Criteria) this;
        }

        public Criteria andDelivertLikeInsensitive(String value) {
            addCriterion("upper(DELIVERT) like", value.toUpperCase(), "delivert");
            return (Criteria) this;
        }

        public Criteria andPositionLikeInsensitive(String value) {
            addCriterion("upper(POSITION) like", value.toUpperCase(), "position");
            return (Criteria) this;
        }

        public Criteria andIsDisplayLikeInsensitive(String value) {
            addCriterion("upper(IS_DISPLAY) like", value.toUpperCase(), "isDisplay");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 15 09:28:24 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}