package com.mmbao.redis.dao.mybatis.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class XmallDxDlDz implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XMALL_DXDL_DZ.DZ_ID
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    private String dzId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XMALL_DXDL_DZ.DZ_TYPE
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    private String dzType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XMALL_DXDL_DZ.DZ_STANDARD
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    private String dzStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XMALL_DXDL_DZ.VOLTAGE
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    private String voltage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XMALL_DXDL_DZ.DELIVERT
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    private String delivert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XMALL_DXDL_DZ.REFERENCE_PRC
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    private BigDecimal referencePrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XMALL_DXDL_DZ.POSITION
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XMALL_DXDL_DZ.SORTNUM
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    private BigDecimal sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XMALL_DXDL_DZ.IS_DISPLAY
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    private String isDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XMALL_DXDL_DZ.CREATE_DATE
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_XMALL_DXDL_DZ.MODIFY_DATE
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XMALL_DXDL_DZ.DZ_ID
     *
     * @return the value of T_XMALL_DXDL_DZ.DZ_ID
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public String getDzId() {
        return dzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XMALL_DXDL_DZ.DZ_ID
     *
     * @param dzId the value for T_XMALL_DXDL_DZ.DZ_ID
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setDzId(String dzId) {
        this.dzId = dzId == null ? null : dzId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XMALL_DXDL_DZ.DZ_TYPE
     *
     * @return the value of T_XMALL_DXDL_DZ.DZ_TYPE
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public String getDzType() {
        return dzType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XMALL_DXDL_DZ.DZ_TYPE
     *
     * @param dzType the value for T_XMALL_DXDL_DZ.DZ_TYPE
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setDzType(String dzType) {
        this.dzType = dzType == null ? null : dzType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XMALL_DXDL_DZ.DZ_STANDARD
     *
     * @return the value of T_XMALL_DXDL_DZ.DZ_STANDARD
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public String getDzStandard() {
        return dzStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XMALL_DXDL_DZ.DZ_STANDARD
     *
     * @param dzStandard the value for T_XMALL_DXDL_DZ.DZ_STANDARD
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setDzStandard(String dzStandard) {
        this.dzStandard = dzStandard == null ? null : dzStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XMALL_DXDL_DZ.VOLTAGE
     *
     * @return the value of T_XMALL_DXDL_DZ.VOLTAGE
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public String getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XMALL_DXDL_DZ.VOLTAGE
     *
     * @param voltage the value for T_XMALL_DXDL_DZ.VOLTAGE
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setVoltage(String voltage) {
        this.voltage = voltage == null ? null : voltage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XMALL_DXDL_DZ.DELIVERT
     *
     * @return the value of T_XMALL_DXDL_DZ.DELIVERT
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public String getDelivert() {
        return delivert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XMALL_DXDL_DZ.DELIVERT
     *
     * @param delivert the value for T_XMALL_DXDL_DZ.DELIVERT
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setDelivert(String delivert) {
        this.delivert = delivert == null ? null : delivert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XMALL_DXDL_DZ.REFERENCE_PRC
     *
     * @return the value of T_XMALL_DXDL_DZ.REFERENCE_PRC
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public BigDecimal getReferencePrc() {
        return referencePrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XMALL_DXDL_DZ.REFERENCE_PRC
     *
     * @param referencePrc the value for T_XMALL_DXDL_DZ.REFERENCE_PRC
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setReferencePrc(BigDecimal referencePrc) {
        this.referencePrc = referencePrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XMALL_DXDL_DZ.POSITION
     *
     * @return the value of T_XMALL_DXDL_DZ.POSITION
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XMALL_DXDL_DZ.POSITION
     *
     * @param position the value for T_XMALL_DXDL_DZ.POSITION
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XMALL_DXDL_DZ.SORTNUM
     *
     * @return the value of T_XMALL_DXDL_DZ.SORTNUM
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public BigDecimal getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XMALL_DXDL_DZ.SORTNUM
     *
     * @param sortnum the value for T_XMALL_DXDL_DZ.SORTNUM
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setSortnum(BigDecimal sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XMALL_DXDL_DZ.IS_DISPLAY
     *
     * @return the value of T_XMALL_DXDL_DZ.IS_DISPLAY
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public String getIsDisplay() {
        return isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XMALL_DXDL_DZ.IS_DISPLAY
     *
     * @param isDisplay the value for T_XMALL_DXDL_DZ.IS_DISPLAY
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setIsDisplay(String isDisplay) {
        this.isDisplay = isDisplay == null ? null : isDisplay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XMALL_DXDL_DZ.CREATE_DATE
     *
     * @return the value of T_XMALL_DXDL_DZ.CREATE_DATE
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XMALL_DXDL_DZ.CREATE_DATE
     *
     * @param createDate the value for T_XMALL_DXDL_DZ.CREATE_DATE
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_XMALL_DXDL_DZ.MODIFY_DATE
     *
     * @return the value of T_XMALL_DXDL_DZ.MODIFY_DATE
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_XMALL_DXDL_DZ.MODIFY_DATE
     *
     * @param modifyDate the value for T_XMALL_DXDL_DZ.MODIFY_DATE
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}