package com.mmbao.redis.dao.mybatis.persistence;

import com.mmbao.redis.dao.mybatis.domain.XmallDxDlDz;
import com.mmbao.redis.dao.mybatis.domain.XmallDxDlDzExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface XmallDxDlDzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    int countByExample(XmallDxDlDzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    int deleteByExample(XmallDxDlDzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    int deleteByPrimaryKey(String dzId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    int insert(XmallDxDlDz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    int insertSelective(XmallDxDlDz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    List<XmallDxDlDz> selectByExample(XmallDxDlDzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    XmallDxDlDz selectByPrimaryKey(String dzId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") XmallDxDlDz record, @Param("example") XmallDxDlDzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    int updateByExample(@Param("record") XmallDxDlDz record, @Param("example") XmallDxDlDzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    int updateByPrimaryKeySelective(XmallDxDlDz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_XMALL_DXDL_DZ
     *
     * @mbggenerated Tue Mar 15 09:28:24 CST 2016
     */
    int updateByPrimaryKey(XmallDxDlDz record);
}